------------------------------------------------------------
-- Events Pipeline: DEV Environment Setup
-- Step 1: Database, Schemas, Role, and Grants
-- Run with ACCOUNTADMIN (one-time setup)
------------------------------------------------------------

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS EVENTS_DEV;
CREATE SCHEMA IF NOT EXISTS EVENTS_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS EVENTS_DEV.BRONZE;
CREATE SCHEMA IF NOT EXISTS EVENTS_DEV.SILVER;
CREATE SCHEMA IF NOT EXISTS EVENTS_DEV.GOLD;
CREATE SCHEMA IF NOT EXISTS EVENTS_DEV.ORCH;

CREATE ROLE IF NOT EXISTS EVENTS_DEV_ROLE;
GRANT ROLE EVENTS_DEV_ROLE TO USER MCHARNI;

GRANT USAGE ON DATABASE EVENTS_DEV TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON SCHEMA EVENTS_DEV.RAW TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON SCHEMA EVENTS_DEV.BRONZE TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON SCHEMA EVENTS_DEV.SILVER TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON SCHEMA EVENTS_DEV.GOLD TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON SCHEMA EVENTS_DEV.ORCH TO ROLE EVENTS_DEV_ROLE;

GRANT ALL ON FUTURE TABLES IN SCHEMA EVENTS_DEV.RAW TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA EVENTS_DEV.BRONZE TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA EVENTS_DEV.SILVER TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA EVENTS_DEV.GOLD TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA EVENTS_DEV.ORCH TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE STAGES IN SCHEMA EVENTS_DEV.RAW TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE STREAMS IN SCHEMA EVENTS_DEV.RAW TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE TASKS IN SCHEMA EVENTS_DEV.RAW TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA EVENTS_DEV.ORCH TO ROLE EVENTS_DEV_ROLE;
GRANT ALL ON FUTURE FILE FORMATS IN SCHEMA EVENTS_DEV.RAW TO ROLE EVENTS_DEV_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE EVENTS_DEV_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE EVENTS_DEV_ROLE;
