------------------------------------------------------------
-- Events Pipeline: Orchestration Objects
-- Step 4: Batch audit, watermarks, and orchestration procedures
-- Run with EVENTS_DEV_ROLE
------------------------------------------------------------

USE ROLE EVENTS_DEV_ROLE;
USE DATABASE EVENTS_DEV;
USE SCHEMA ORCH;
USE WAREHOUSE COMPUTE_WH;

CREATE TABLE IF NOT EXISTS EVENTS_DEV.ORCH.BATCH_AUDIT (
  BATCH_ID              STRING        NOT NULL,
  SOURCE_NAME           STRING,
  ENTITY_NAME           STRING,
  STAGE_PATH            STRING,
  AIRFLOW_RUN_ID        STRING,
  STATUS                STRING        DEFAULT 'PENDING',
  RECORD_COUNT_EXPECTED NUMBER,
  RECORD_COUNT_LOADED   NUMBER,
  CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ERROR_MESSAGE         STRING
);

CREATE TABLE IF NOT EXISTS EVENTS_DEV.ORCH.WATERMARKS (
  ENTITY_NAME    STRING PRIMARY KEY,
  LAST_WATERMARK STRING,
  LAST_BATCH_ID  STRING,
  UPDATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE EVENTS_DEV.ORCH.REGISTER_BATCH(
  P_BATCH_ID STRING,
  P_SOURCE_NAME STRING,
  P_ENTITY_NAME STRING,
  P_STAGE_PATH STRING,
  P_AIRFLOW_RUN_ID STRING,
  P_RECORD_COUNT NUMBER
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO EVENTS_DEV.ORCH.BATCH_AUDIT (
    BATCH_ID, SOURCE_NAME, ENTITY_NAME, STAGE_PATH,
    AIRFLOW_RUN_ID, STATUS, RECORD_COUNT_EXPECTED, CREATED_AT, UPDATED_AT
  )
  VALUES (
    :P_BATCH_ID, :P_SOURCE_NAME, :P_ENTITY_NAME, :P_STAGE_PATH,
    :P_AIRFLOW_RUN_ID, 'UPLOADED', :P_RECORD_COUNT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
  );
  RETURN 'BATCH_REGISTERED';
END;
$$;

CREATE OR REPLACE PROCEDURE EVENTS_DEV.ORCH.UPDATE_BATCH_STATUS(
  P_BATCH_ID STRING,
  P_STATUS STRING,
  P_RECORD_COUNT_LOADED NUMBER DEFAULT NULL,
  P_ERROR_MESSAGE STRING DEFAULT NULL
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  UPDATE EVENTS_DEV.ORCH.BATCH_AUDIT
  SET STATUS = :P_STATUS,
      RECORD_COUNT_LOADED = COALESCE(:P_RECORD_COUNT_LOADED, RECORD_COUNT_LOADED),
      ERROR_MESSAGE = :P_ERROR_MESSAGE,
      UPDATED_AT = CURRENT_TIMESTAMP()
  WHERE BATCH_ID = :P_BATCH_ID;
  RETURN 'STATUS_UPDATED';
END;
$$;
